server:
  port: 8080
#Set yours database information
spring:
  datasource:
    url: jdbc:oracle:thin:@1.12.62.6:1521/helowin
    username: theking
    password: cjs524821
    driver-class-name: oracle.jdbc.OracleDriver
