server:
  port: 8080
#Set yours database information
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1522/ORCL11g
    username: DMYXYG
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
